spring.application.name=sistema-ventas

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bd_zippers?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1103
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- CONFIGURACIÓN DE SUBIDA DE ARCHIVOS MULTIMEDIA ---
spring.servlet.multipart.max-file-size=14MB
spring.servlet.multipart.max-request-size=70MB